# -*- coding: utf-8 -*-
"""config

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kgWh0muN4K7ewcFdm0mLL8S9z5CMaDW-
"""

from pathlib import Path
import os
import json
import sqlite3
import logging
import numpy as np
import pandas as pd

ROOT = Path(os.getcwd())

RAW_DIR = ROOT
SOURCE_DB = ROOT / "store.db"
WAREHOUSE_DB = ROOT / "warehouse.db"
OUTPUT_DIR = ROOT / "output"
LOG_DIR = ROOT / "logs"

PROVINCE_MAP = {
    "chonburi": "Chonburi",
    "chon buri": "Chonburi",
    "ชลบุรี": "Chonburi",
    "bangkok": "Bangkok",
    "bkk": "Bangkok",
    "กรุงเทพฯ": "Bangkok",
    "rayong": "Rayong",
    "ระยอง": "Rayong",
    "chanthaburi": "Chanthaburi",
    "chantaburi": "Chanthaburi",
    "จันทบุรี": "Chanthaburi",
}

VALID_ORDER_STATUSES = {"paid", "completed"}

DATE_FORMATS = [
    "%Y-%m-%d",
    "%Y/%m/%d",
    "%d/%m/%Y",
    "%m/%d/%Y",
    "%d-%m-%Y",
    "%m-%d-%Y",
    "%d %b %Y",
    "%d %B %Y",
    "%b %d, %Y",
    "%B %d, %Y",
]