# -*- coding: utf-8 -*-
"""extract

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kgWh0muN4K7ewcFdm0mLL8S9z5CMaDW-
"""

import json
import sqlite3
import logging
import pandas as pd

logger = logging.getLogger(__name__)

def _load_products_json(path):
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)

    if isinstance(data, dict):
        list_values = [v for v in data.values() if isinstance(v, list)]
        records = list_values[0] if list_values else [data]
    else:
        records = data

    return pd.json_normalize(records)

def extract_data():
    customers_path = RAW_DIR / "customers.csv"
    orders_path = RAW_DIR / "orders.csv"
    products_path = RAW_DIR / "products.json"

    customers = pd.read_csv(customers_path)
    orders = pd.read_csv(orders_path)
    products = _load_products_json(products_path)

    conn = sqlite3.connect(SOURCE_DB)
    try:
        stores = pd.read_sql_query("SELECT * FROM stores", conn)
    finally:
        conn.close()

    logger.info("Extracted customers: shape=%s columns=%s", customers.shape, list(customers.columns))
    logger.info("Extracted orders: shape=%s columns=%s", orders.shape, list(orders.columns))
    logger.info("Extracted products: shape=%s columns=%s", products.shape, list(products.columns))
    logger.info("Extracted stores: shape=%s columns=%s", stores.shape, list(stores.columns))

    raw = {
        "customers": customers,
        "orders": orders,
        "products": products,
        "stores": stores,
    }
    return raw