# -*- coding: utf-8 -*-
"""load

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kgWh0muN4K7ewcFdm0mLL8S9z5CMaDW-
"""

SCHEMA = """
CREATE TABLE IF NOT EXISTS dim_customer (
    customer_id TEXT PRIMARY KEY,
    name        TEXT,
    province    TEXT,
    email       TEXT
);

CREATE TABLE IF NOT EXISTS dim_product (
    product_id   TEXT PRIMARY KEY,
    product_name TEXT,
    category     TEXT,
    price        REAL
);

CREATE TABLE IF NOT EXISTS fact_sales (
    order_id      TEXT PRIMARY KEY,
    customer_id   TEXT,
    product_id    TEXT,
    order_date    TEXT,
    qty           REAL,
    unit_price    REAL,
    discount_pct  REAL,
    sales_amount  REAL,
    FOREIGN KEY (customer_id) REFERENCES dim_customer (customer_id),
    FOREIGN KEY (product_id)  REFERENCES dim_product (product_id)
);
"""


def load_data(customers, products, sales):
    WAREHOUSE_DB.parent.mkdir(parents=True, exist_ok=True)

    conn = sqlite3.connect(WAREHOUSE_DB)
    try:
        cur = conn.cursor()
        cur.executescript(SCHEMA)

        cust_rows = list(
            customers[["customer_id", "name", "province", "email"]].itertuples(
                index=False, name=None
            )
        )
        cur.executemany(
            """INSERT INTO dim_customer (customer_id, name, province, email)
               VALUES (?, ?, ?, ?)
               ON CONFLICT(customer_id) DO UPDATE SET
                   name=excluded.name,
                   province=excluded.province,
                   email=excluded.email""",
            cust_rows,
        )

        prod_rows = list(
            products[["product_id", "product_name", "category", "price"]].itertuples(
                index=False, name=None
            )
        )
        cur.executemany(
            """INSERT INTO dim_product (product_id, product_name, category, price)
               VALUES (?, ?, ?, ?)
               ON CONFLICT(product_id) DO UPDATE SET
                   product_name=excluded.product_name,
                   category=excluded.category,
                   price=excluded.price""",
            prod_rows,
        )

        sales_df = sales.copy()
        sales_df["order_date"] = sales_df["order_date"].astype(str)
        sales_rows = list(
            sales_df[
                [
                    "order_id",
                    "customer_id",
                    "product_id",
                    "order_date",
                    "qty",
                    "unit_price",
                    "discount_pct",
                    "sales_amount",
                ]
            ].itertuples(index=False, name=None)
        )
        cur.executemany(
            """INSERT INTO fact_sales
                   (order_id, customer_id, product_id, order_date,
                    qty, unit_price, discount_pct, sales_amount)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?)
               ON CONFLICT(order_id) DO UPDATE SET
                   customer_id=excluded.customer_id,
                   product_id=excluded.product_id,
                   order_date=excluded.order_date,
                   qty=excluded.qty,
                   unit_price=excluded.unit_price,
                   discount_pct=excluded.discount_pct,
                   sales_amount=excluded.sales_amount""",
            sales_rows,
        )

        conn.commit()
        logger.info(
            "Loaded warehouse: %d customers, %d products, %d sales rows (upsert)",
            len(cust_rows),
            len(prod_rows),
            len(sales_rows),
        )
    finally:
        conn.close()