# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kgWh0muN4K7ewcFdm0mLL8S9z5CMaDW-
"""

import json

def main():
    LOG_DIR.mkdir(parents=True, exist_ok=True)
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s | %(levelname)s | %(message)s",
        handlers=[
            logging.FileHandler(LOG_DIR / "etl.log", encoding="utf-8"),
            logging.StreamHandler(),
        ],
        force=True,
    )

    logging.info("ETL started")

    raw = extract_data()
    customers, products, sales, rejects = transform_data(raw)

    rejects.to_csv(OUTPUT_DIR / "rejects.csv", index=False)
    logging.info("Wrote %d reject rows to output/rejects.csv", len(rejects))

    load_data(customers, products, sales)

    result = validate_data(sales)
    (OUTPUT_DIR / "validation.json").write_text(
        json.dumps(result, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    logging.info("ETL completed")
    print(json.dumps(result, ensure_ascii=False, indent=2))

main()