# -*- coding: utf-8 -*-
"""transform

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kgWh0muN4K7ewcFdm0mLL8S9z5CMaDW-
"""

import pandas as pd

def _standardize_province(value):
    if pd.isna(value):
        return None
    key = str(value).strip().lower()
    return PROVINCE_MAP.get(key, str(value).strip().title())

def _clean_customers(customers_raw):
    df = customers_raw.copy()
    df.columns = [c.strip().lower() for c in df.columns]

    before = len(df)
    df = df.drop_duplicates(subset="customer_id", keep="first")
    logger.info("Customers: dropped %d duplicate customer_id rows", before - len(df))

    if "province" in df.columns:
        df["province"] = df["province"].apply(_standardize_province)
        df["province"] = df["province"].fillna("Unknown")
    else:
        df["province"] = "Unknown"

    if "email" in df.columns:
        df["email"] = df["email"].astype(str).str.strip()
        df.loc[df["email"].isin(["", "nan", "None"]), "email"] = "unknown@example.com"
        df["email"] = df["email"].fillna("unknown@example.com")
    else:
        df["email"] = "unknown@example.com"

    if "name" in df.columns:
        df["name"] = df["name"].fillna("Unknown").astype(str).str.strip()
    else:
        df["name"] = "Unknown"

    return df.reset_index(drop=True)

def _clean_products(products_raw):
    df = products_raw.copy()
    df.columns = [str(c).strip() for c in df.columns]

    explicit_map = {
        "category.name": "category",
        "category_name": "category",
        "pricing.price": "price",
        "pricing.amount": "price",
        "price.amount": "price",
    }
    for col in list(df.columns):
        key = col.lower()
        if key in explicit_map:
            target = explicit_map[key]
            if target in df.columns:
                df[target] = df[target].fillna(df[col])
                df = df.drop(columns=[col])
            else:
                df = df.rename(columns={col: target})

    df.columns = [
        str(c).split(".")[-1].strip().lower() if "." in str(c) else str(c).strip().lower()
        for c in df.columns
    ]

    generic_map = {
        "id": "product_id",
        "productid": "product_id",
        "name": "product_name",
        "productname": "product_name",
        "title": "product_name",
        "cat": "category",
        "amount": "price",
        "unit_price": "price",
    }
    for src, target in generic_map.items():
        if src in df.columns and src != target:
            if target in df.columns:
                df[target] = df[target].fillna(df[src])
                df = df.drop(columns=[src])
            else:
                df = df.rename(columns={src: target})

    if "price" in df.columns:
        df["price"] = pd.to_numeric(
            df["price"].astype(str).str.replace(r"[^\d.\-]", "", regex=True),
            errors="coerce",
        )
    else:
        df["price"] = np.nan

    if "category" in df.columns:
        df["category"] = df["category"].astype(str).str.strip()
        df.loc[df["category"].isin(["", "nan", "None"]), "category"] = "Unknown"
        df["category"] = df["category"].fillna("Unknown")
    else:
        df["category"] = "Unknown"

    if "product_name" not in df.columns:
        df["product_name"] = "Unknown"
    df["product_name"] = df["product_name"].fillna("Unknown")

    before = len(df)
    df = df.drop_duplicates(subset="product_id", keep="first")
    logger.info("Products: dropped %d duplicate product_id rows", before - len(df))

    return df.reset_index(drop=True)

def _parse_mixed_date(value):
    if pd.isna(value):
        return pd.NaT
    s = str(value).strip()
    if s == "" or s.lower() == "nan":
        return pd.NaT

    for fmt in DATE_FORMATS:
        try:
            return pd.to_datetime(s, format=fmt)
        except (ValueError, TypeError):
            continue

    return pd.to_datetime(s, errors="coerce")

def _clean_orders(orders_raw):
    df = orders_raw.copy()
    df.columns = [c.strip().lower() for c in df.columns]

    before = len(df)
    df = df.drop_duplicates(subset="order_id", keep="first")
    logger.info("Orders: dropped %d duplicate order_id rows", before - len(df))

    if "status" in df.columns:
        df["status"] = df["status"].astype(str).str.strip().str.lower()
    else:
        df["status"] = ""

    date_col = "order_date" if "order_date" in df.columns else None
    if date_col is None:
        candidates = [c for c in df.columns if "date" in c]
        date_col = candidates[0] if candidates else None

    df["order_date_parsed"] = df[date_col].apply(_parse_mixed_date) if date_col else pd.NaT

    for col in ["qty", "unit_price", "discount_pct"]:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")
        else:
            df[col] = np.nan

    return df.reset_index(drop=True)

def transform_data(raw):
    customers = _clean_customers(raw["customers"])
    products = _clean_products(raw["products"])
    orders = _clean_orders(raw["orders"])

    reject_records = []

    def _add_rejects(frame, reason):
        if frame.empty:
            return
        tmp = frame.drop(columns=["order_date_parsed", "_reason"], errors="ignore").copy()
        tmp["reject_reason"] = reason
        reject_records.append(tmp)

    invalid_qty = orders["qty"].isna() | (orders["qty"] <= 0)
    invalid_price = orders["unit_price"].isna() | (orders["unit_price"] <= 0)
    invalid_discount = (
        orders["discount_pct"].isna()
        | (orders["discount_pct"] < 0)
        | (orders["discount_pct"] > 100)
    )
    invalid_date = orders["order_date_parsed"].isna()

    reason = np.select(
        [invalid_qty, invalid_price, invalid_discount, invalid_date],
        ["invalid_qty", "invalid_unit_price", "invalid_discount_pct", "invalid_order_date"],
        default="",
    )
    orders["_reason"] = reason

    for r in ["invalid_qty", "invalid_unit_price", "invalid_discount_pct", "invalid_order_date"]:
        _add_rejects(orders[orders["_reason"] == r], r)

    orders_ok = orders[orders["_reason"] == ""].drop(columns=["_reason"]).copy()

    keep_status = orders_ok["status"].isin(VALID_ORDER_STATUSES)
    _add_rejects(orders_ok[~keep_status], "status_not_paid_or_completed")
    orders_ok = orders_ok[keep_status].copy()

    valid_customer_ids = set(customers["customer_id"])
    valid_product_ids = set(products["product_id"])

    missing_customer = ~orders_ok["customer_id"].isin(valid_customer_ids)
    _add_rejects(orders_ok[missing_customer], "unknown_customer_id")
    orders_ok = orders_ok[~missing_customer].copy()

    missing_product = ~orders_ok["product_id"].isin(valid_product_ids)
    _add_rejects(orders_ok[missing_product], "unknown_product_id")
    orders_ok = orders_ok[~missing_product].copy()

    merged = orders_ok.merge(
        customers[["customer_id", "name", "province", "email"]],
        on="customer_id",
        how="left",
    )
    merged = merged.merge(
        products[["product_id", "product_name", "category", "price"]],
        on="product_id",
        how="left",
        suffixes=("", "_catalog"),
    )

    merged["gross_amount"] = merged["qty"] * merged["unit_price"]
    merged["discount_amount"] = merged["gross_amount"] * merged["discount_pct"] / 100
    merged["sales_amount"] = merged["gross_amount"] - merged["discount_amount"]
    merged["order_date"] = merged["order_date_parsed"]

    sales = merged[
        [
            "order_id",
            "customer_id",
            "product_id",
            "order_date",
            "qty",
            "unit_price",
            "discount_pct",
            "sales_amount",
        ]
    ].reset_index(drop=True)

    if reject_records:
        rejects = pd.concat(reject_records, ignore_index=True, sort=False)
    else:
        rejects = pd.DataFrame(columns=list(orders.columns) + ["reject_reason"])

    logger.info(
        "Transform complete: %d valid sales rows, %d rejected rows", len(sales), len(rejects)
    )

    return customers, products, sales, rejects