# -*- coding: utf-8 -*-
"""validate

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kgWh0muN4K7ewcFdm0mLL8S9z5CMaDW-
"""

def validate_data(source_sales):
    conn = sqlite3.connect(WAREHOUSE_DB)
    try:
        warehouse_df = pd.read_sql_query("SELECT * FROM fact_sales", conn)
    finally:
        conn.close()

    source_valid_rows = int(len(source_sales))
    warehouse_rows = int(len(warehouse_df))
    duplicate_order_ids = int(warehouse_df["order_id"].duplicated().sum())

    source_total_sales = round(float(source_sales["sales_amount"].sum()), 2)
    warehouse_total_sales = round(float(warehouse_df["sales_amount"].sum()), 2)

    checks_passed = (
        source_valid_rows == warehouse_rows
        and duplicate_order_ids == 0
        and abs(source_total_sales - warehouse_total_sales) < 0.01
    )
    status = "PASS" if checks_passed else "FAIL"

    result = {
        "source_valid_rows": source_valid_rows,
        "warehouse_rows": warehouse_rows,
        "duplicate_order_ids": duplicate_order_ids,
        "source_total_sales": source_total_sales,
        "warehouse_total_sales": warehouse_total_sales,
        "status": status,
    }

    logger.info("Validation result: %s", result)
    return result